=== api-evangelist/amazon-managed-grafana/json-schema/amazon-managed-grafana-create-workspace-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-managed-grafana/refs/heads/main/json-schema/amazon-managed-grafana-create-workspace-request-schema.json",
  "title": "CreateWorkspaceRequest",
  "description": "CreateWorkspaceRequest schema from Amazon Managed Grafana API",
  "type": "object",
  "properties": {
    "accountAccessType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AccountAccessType"
        },
        {
          "description": "Specifies whether the workspace can access Amazon Web Services resources in this Amazon Web Services account only, or whether it can also access Amazon Web Services resources in other accounts in the same organization. If you specify <code>ORGANIZATION</code>, you must specify which organizational units the workspace can access in the <code>workspaceOrganizationalUnits</code> parameter."
        }
      ]
    },
    "authenticationProviders": {
      "allOf": [
        {
          "$ref": "#/components/schemas/AuthenticationProviders"
        },
        {
          "description": "Specifies whether this workspace uses SAML 2.0, IAM Identity Center (successor to Single Sign-On), or both to authenticate users for using the Grafana console within a workspace. For more information, see <a href=\"https://docs.aws.amazon.com/grafana/latest/userguide/authentication-in-AMG.html\">User authentication in Amazon Managed Grafana</a>."
        }
      ]
    },
    "clientToken": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientToken"
        },
        {
          "description": "A unique, case-sensitive, user-provided identifier to ensure the idempotency of the request."
        }
      ]
    },
    "configuration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OverridableConfigurationJson"
        },
        {
          "description": "The configuration string for the workspace that you create. For more information about the format and configuration options available, see <a href=\"https://docs.aws.amazon.com/grafana/latest/userguide/AMG-configure-workspace.html\">Working in your Grafana workspace</a>."
        }
      ]
    },
    "grafanaVersion": {
      "allOf": [
        {
          "$ref": "#/components/schemas/GrafanaVersion"
        },
        {
          "description": "<p>Specifies the version of Grafana to support in the new workspace.</p> <p>To get a list of supported version, use the <code>ListVersions</code> operation.</p>"
        }
      ]
    },
    "networkAccessControl": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NetworkAccessConfiguration"
        },
        {
          "description": "<p>Configuration for network access to your workspace.</p> <p>When this is configured, only listed IP addresses and VPC endpoints will be able to access your workspace. Standard Grafana authentication and authorization will still be required.</p> <p>If this is not configured, or is removed, then all IP addresses and VPC endpoints will be allowed. Standard Grafana authentication and authorization will still be required.</p>"
        }
      ]
    },
    "organizationRoleName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OrganizationRoleName"
        },
        {
          "description": "The name of an IAM role that already exists to use with Organizations to access Amazon Web Services data sources and notification channels in other accounts in an organization."
        }
      ]
    },
    "permissionType": {
      "allOf": [
        {
          "$ref": "#/components/schemas/PermissionType"
        },
        {
          "description": "<p>When creating a workspace through the Amazon Web Services API, CLI or Amazon Web Services CloudFormation, you must manage IAM roles and provision the permissions that the workspace needs to use Amazon Web Services data sources and notification channels.</p> <p>You must also specify a <code>workspaceRoleArn</code> for a role that you will manage for the workspace to use when accessing those datasources and notification channels.</p> <p>The ability for Amazon Managed Grafana to create and update IAM roles on behalf of the user is supported only in the Amazon Managed Grafana console, where this value may be set to <code>SERVICE_MANAGED</code>.</p> <note> <p>Use only the <code>CUSTOMER_MANAGED</code> permission type when creating a workspace with the API, CLI or Amazon Web Services CloudFormation. </p> </note> <p>For more information, see <a href=\"https://docs.aws.amazon.com/grafana/latest/userguide/AMG-manage-permissions.html\">Amazon Managed Grafana permissions and policies for Amazon Web Services data sources and notification channels</a>.</p>"
        }
      ]
    },
    "stackSetName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StackSetName"
        },
        {
          "description": "The name of the CloudFormation stack set to use to generate IAM roles to be used for this workspace."
        }
      ]
    },
    "tags": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TagMap"
        },
        {
          "description": "The list of tags associated with the workspace."
        }
      ]
    },
    "vpcConfiguration": {
      "allOf": [
        {
          "$ref": "#/components/schemas/VpcConfiguration"
        },
        {
          "description": "<p>The configuration settings for an Amazon VPC that contains data sources for your Grafana workspace to connect to.</p> <note> <p>Connecting to a private VPC is not yet available in the Asia Pacific (Seoul) Region (ap-northeast-2).</p> </note>"
        }
      ]
    },
    "workspaceDataSources": {
      "allOf": [
        {
          "$ref": "#/components/schemas/DataSourceTypesList"
        },
        {
          "description": "This parameter is for internal use only, and should not be used."
        }
      ]
    },
    "workspaceDescription": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Description"
        },
        {
          "description": "<p>A description for the workspace. This is used only to help you identify this workspace.</p> <p>Pattern: <code>^[\\\\p{L}\\\\p{Z}\\\\p{N}\\\\p{P}]{0,2048}$</code> </p>"
        }
      ]
    },
    "workspaceName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/WorkspaceName"
        },
        {
          "description": "The name for the workspace. It does not have to be unique."
        }
      ]
    },
    "workspaceNotificationDestinations": {
      "allOf": [
        {
          "$ref": "#/components/schemas/NotificationDestinationsList"
        },
        {
          "description": "Specify the Amazon Web Services notification channels that you plan to use in this workspace. Specifying these data sources here enables Amazon Managed Grafana to create IAM roles and permissions that allow Amazon Managed Grafana to use these channels."
        }
      ]
    },
    "workspaceOrganizationalUnits": {
      "allOf": [
        {
          "$ref": "#/components/schemas/OrganizationalUnitList"
        },
        {
          "description": "Specifies the organizational units that this workspace is allowed to use data sources from, if this workspace is in an account that is part of an organization."
        }
      ]
    },
    "workspaceRoleArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/IamRoleArn"
        },
        {
          "description": "Specified the IAM role that grants permissions to the Amazon Web Services resources that the workspace will view data from, including both data sources and notification channels. You are responsible for managing the permissions for this role as new data sources or notification channels are added. "
        }
      ]
    }
  },
  "required": [
    "accountAccessType",
    "authenticationProviders",
    "permissionType"
  ]
}

=== api-evangelist/amazon-managed-grafana/examples/amazon-managed-grafana-create-workspace-request-example.json
{
  "accountAccessType": "example-value",
  "authenticationProviders": "abc12345",
  "clientToken": "example-value",
  "configuration": "example-value",
  "grafanaVersion": "example-value",
  "networkAccessControl": "example-value",
  "organizationRoleName": "my-resource",
  "permissionType": "example-value",
  "stackSetName": "my-resource",
  "tags": "example-value",
  "vpcConfiguration": "example-value",
  "workspaceDataSources": "example-value",
  "workspaceDescription": "Example resource description",
  "workspaceName": "my-resource",
  "workspaceNotificationDestinations": "example-value",
  "workspaceOrganizationalUnits": "example-value",
  "workspaceRoleArn": "arn:aws:service:us-east-1:123456789012:resource/id"
}
